version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'bbortt'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'bbortt'
