name: build
on:
  push:
    branches:
      - '**/*'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: postfinance/polling-swagger-ui
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Test
        run: |
          docker run \
            --rm \
            --name swagger-ui-test \
            -p 8080:8080 \
            -e POLL_INTERVAL_SECONDS=60 \
            -e POLL_URL=https://raw.githubusercontent.com/bbortt/swagger-ui-demo/master/swagger-config.json \
            ${{ steps.meta.outputs.tags }} & \
          (
            sleep 10 && \
            if [[ $(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/apis/pet-api.json) -ne 200 ]]; then
              exit 1;
            fi && \
            if [[ $(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/apis/store-api.json) -ne 200 ]]; then
              exit 1;
            fi && \
            docker container stop swagger-ui-test
          )
